theme = "base16_transparent"

[editor]
bufferline = "multiple"
mouse = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

